variables:
  GIT_STRATEGY: fetch

stages:
  - build
  - pages

build:
  stage: build
  script:
    - nix-build -A production
    - realpath result > result-path
  artifacts:
    paths:
      - result-path

pages:
  stage: pages
  script:
    - nix-shell -p rsync --run 'rsync -aL --chmod=u+w $(<result-path)/ public/'
  artifacts:
    paths:
      - public/
  only:
    - master
